Group1.3_GradingSystem_Prototype/Models/AdminModel.cs
namespace Group1._3_GradingSystem_Prototype.Models
{
    public class AdminModel
    {
        public string username { get; set; }

        public string password { get; set; }
    }
}

Group1.3_GradingSystem_Prototype/Models/ErrorViewModel.cs
namespace Group1._3_GradingSystem_Prototype.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Group1.3_GradingSystem_Prototype/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Group1._3_GradingSystem_Prototype.Models;


namespace Group1._3_GradingSystem_Prototype.Controllers
{
    public class AdminController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult AdminHomePage()
        {
            return View();
        }

        public ActionResult AdminDashboard()
        {
            return View();
        }

        public ActionResult AdminLoginPage()
        {
            return View();
        }
    }
}

Group1.3_GradingSystem_Prototype/Controllers/HomeController.cs
using Group1._3_GradingSystem_Prototype.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Group1._3_GradingSystem_Prototype.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public ActionResult TeacherLoginPage()
        {
            return View();
        }
        public ActionResult StudentLoginPage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Group1.3_GradingSystem_Prototype/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Group1._3_GradingSystem_Prototype.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult StudentLoginPage()
        {
            return View();
        }
    }
}

Group1.3_GradingSystem_Prototype/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;

namespace Group1._3_GradingSystem_Prototype.Controllers
{
    public class TeacherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult TeacherLoginPage()
        {
            return View();
        }
    }
}

Group1.3_GradingSystem_Prototype/Views/Admin/AdminDashboard.cshtml
@{
    ViewData["Title"] = "Admin Dashboard";
    Layout = "AdminLayout";
}
<div class="admin-home-container">
    <div class="admin-content">
        <div class="admin-main-content">
            <div class="admin-dashboard-welcome">
                <h3 class="admin-dashboard-welcome">Welcome to the dashboard, Admin!</h3>
            </div>
        </div>
    </div>
</div>

Group1.3_GradingSystem_Prototype/Views/Admin/AdminHomePage.cshtml
@{
    ViewData["Title"] = "Admin Home";
    Layout = "AdminLayout";
}
<div class="admin-home-container">
    <div class="admin-content">
        <div class="admin-main-content">
            <img class="admin-home-image" src=@Url.Content("~/imgs/Admin-Placeholder.png") />
        </div>
    </div>
</div>

Group1.3_GradingSystem_Prototype/Views/Admin/AdminLoginPage.cshtml
@{
    ViewData["Title"] = "Hope Integrated School";
}

<div class="text-center">
    <div class="logincontainer">
        <div class="login">
            <div class="loginform">
                <div class="login-Hopelogo">
                    <img class="Hopelogo" src=@Url.Content("~/imgs/HIS-Logo.png") />
                </div>
                <h1 class="login-school">HOPE INTEGRATED SCHOOL</h1>
                <div class="login-user-label">
                    <h1 class="login-user-level">Admin Login</h1>
                </div>
                <form class="login-input" action="Verify">
                    <input type="text" id="username" name="username" placeholder="Username" />
                    <input type="password" id="password" name="password" placeholder="Password" />
                    <br />
                    <button type="button" class="btn btn-outline-primary">Login</button>
                </form>
            </div>
            <div class="loginimg">
                <img class="loginimg-image" src=@Url.Content("~/imgs/Placeholder-Login.png") />
            </div>
        </div>
    </div>
</div>

Group1.3_GradingSystem_Prototype/Views/Admin/AdminSubjects.cshtml
@{
    Layout = "AdminLayout";
}
<div class="admin-home-container">
    <div class="admin-content">
        <div class="admin-main-content">
            <img class="admin-home-image" src=@Url.Content("~/imgs/Admin-Placeholder.png") />
        </div>
    </div>
</div>

Group1.3_GradingSystem_Prototype/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Hope Integrated School";
}

Group1.3_GradingSystem_Prototype/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group1._3_GradingSystem_Prototype.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0">
            <img class="Logo" src=@Url.Content("~/imgs/HIS-Logo.png") />
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HOPE INTEGRATED SCHOOL</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="user-dropdown navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown ms-auto">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                        <ul class="dropdown-menu dropdown-menu-end navbar-right" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Logout</a></li>
                        </ul>
                </ul>
            </div>
        </nav>
    </header>
    <div class="admin-sidebar">
        <ul class="admin-sidebar-items nav nav-pills flex-column mb-auto">
            <li class="admin-nav-item">
                <a asp-area="" asp-controller="Admin" asp-action="AdminHomePage" class="nav-link link-dark" aria-current="page">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Home
                </a>
            </li>
            <li class="admin-nav-item">
                <a asp-area="" asp-controller="Admin" asp-action="AdminDashboard" class="nav-link link-dark" aria-current="page">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Dashboard
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Subjects
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Faculty
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Students
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Sections
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    School Year
                </a>
            </li>
            <li class="admin-nav-item">
                <a href="#" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"></svg>
                    Backup
                </a>
            </li>
        </ul>
    </div>
    <div class="admin-container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Group1.3_GradingSystem_Prototype/Views/Shared/DefaultLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group1._3_GradingSystem_Prototype.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <img class="Logo" src=@Url.Content("~/imgs/HIS-Logo.png") />
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HOPE INTEGRATED SCHOOL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown ms-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Login </a>
                            <ul class="dropdown-menu dropdown-menu-end navbar-right" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AdminLoginPage">Admin</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="TeacherLoginPage">Teacher</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="StudentLoginPage">Student</a></li>
                            </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Group1.3_GradingSystem_Prototype/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group1._3_GradingSystem_Prototype.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <img class="Logo" src=@Url.Content("~/imgs/HIS-Logo.png") />
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HOPE INTEGRATED SCHOOL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown ms-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Login </a>
                            <ul class="dropdown-menu dropdown-menu-end navbar-right" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AdminLoginPage">Admin</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="TeacherLoginPage">Teacher</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="StudentLoginPage">Student</a></li>
                            </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Group1.3_GradingSystem_Prototype/Views/Student/StudentLoginPage.cshtml
@{
    ViewData["Title"] = "Hope Integrated School";
}

<div class="text-center">
    <div class="logincontainer">
        <div class="login">
            <div class="loginform">
                <div class="login-Hopelogo">
                    <img class="Hopelogo" src=@Url.Content("~/imgs/HIS-Logo.png") />
                </div>
                    <h1 class="login-school">HOPE INTEGRATED SCHOOL</h1>
                <div class="login-user-label">
                    <h1 class="login-user-level">Student Login</h1>
                </div>
                <form class="login-input">
                    <input type="text" id="username" name="username" placeholder="Username" />
                    <input type="password" id="password" name="password" placeholder="Password" />
                    <br />
                    <button type="button" class="btn btn-outline-primary">Login</button>
                </form>
            </div>
            <div class="loginimg">
                <img class="loginimg-image" src=@Url.Content("~/imgs/Placeholder-Login.png") />
            </div>
        </div>
    </div>
</div>

Group1.3_GradingSystem_Prototype/Views/Teacher/TeacherLoginPage.cshtml
@{
    ViewData["Title"] = "Hope Integrated School";
}

<div class="text-center">
    <div class="logincontainer">
        <div class="login">
            <div class="loginform">
                <div class="login-Hopelogo">
                    <img class="Hopelogo" src=@Url.Content("~/imgs/HIS-Logo.png") />
                </div>
                    <h1 class="login-school">HOPE INTEGRATED SCHOOL</h1>
                <div class="login-user-label">
                    <h1 class="login-user-level">Teacher Login</h1>
                </div>
                <form class="login-input">
                    <input type="text" id="username" name="username" placeholder="Username" />
                    <input type="password" id="password" name="password" placeholder="Password" />
                    <br />
                    <button type="button" class="btn btn-outline-primary">Login</button>
                </form>
            </div>
            <div class="loginimg">
                <img class="loginimg-image" src=@Url.Content("~/imgs/Placeholder-Login.png") />
            </div>
        </div>
    </div>
</div>